package Model;
// Generated Dec 13, 2016 5:57:23 PM by Hibernate Tools 4.3.1


import POJOS.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Advert generated by hbm2java
 */
public class Advert  {


     private Integer id;
     private AdType adType;
     private District district;
     private MainCatagory mainCatagory;
     private SubCatagory subCatagory;
     private User user;
     private String title;
     private String content;
     private Date date;
     private Integer views;
     private Boolean status;
     private Double price;
     private String image;
     private Integer phone;
     private Boolean paid;
     private String email;
     private Set<InvoiceHasAdvert> invoiceHasAdverts = new HashSet<InvoiceHasAdvert>(0);
     private Set<AdReview> adReviews = new HashSet<AdReview>(0);

    public Advert() {
    }

	
    public Advert(AdType adType, District district, MainCatagory mainCatagory, SubCatagory subCatagory, User user) {
        this.adType = adType;
        this.district = district;
        this.mainCatagory = mainCatagory;
        this.subCatagory = subCatagory;
        this.user = user;
    }
    public Advert(AdType adType, District district, MainCatagory mainCatagory, SubCatagory subCatagory, User user, String title, String content, Date date, Integer views, Boolean status, Double price, String image, Integer phone, Boolean paid, String email, Set<InvoiceHasAdvert> invoiceHasAdverts, Set<AdReview> adReviews) {
       this.adType = adType;
       this.district = district;
       this.mainCatagory = mainCatagory;
       this.subCatagory = subCatagory;
       this.user = user;
       this.title = title;
       this.content = content;
       this.date = date;
       this.views = views;
       this.status = status;
       this.price = price;
       this.image = image;
       this.phone = phone;
       this.paid = paid;
       this.email = email;
       this.invoiceHasAdverts = invoiceHasAdverts;
       this.adReviews = adReviews;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AdType getAdType() {
        return this.adType;
    }
    
    public void setAdType(AdType adType) {
        this.adType = adType;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public MainCatagory getMainCatagory() {
        return this.mainCatagory;
    }
    
    public void setMainCatagory(MainCatagory mainCatagory) {
        this.mainCatagory = mainCatagory;
    }
    public SubCatagory getSubCatagory() {
        return this.subCatagory;
    }
    
    public void setSubCatagory(SubCatagory subCatagory) {
        this.subCatagory = subCatagory;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getViews() {
        return this.views;
    }
    
    public void setViews(Integer views) {
        this.views = views;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
    public Boolean getPaid() {
        return this.paid;
    }
    
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<InvoiceHasAdvert> getInvoiceHasAdverts() {
        return this.invoiceHasAdverts;
    }
    
    public void setInvoiceHasAdverts(Set<InvoiceHasAdvert> invoiceHasAdverts) {
        this.invoiceHasAdverts = invoiceHasAdverts;
    }
    public Set<AdReview> getAdReviews() {
        return this.adReviews;
    }
    
    public void setAdReviews(Set<AdReview> adReviews) {
        this.adReviews = adReviews;
    }




}


