package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdType generated by hbm2java
 */
public class AdType  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Double price;
     private Boolean status;
     private Set<Advert> adverts = new HashSet<Advert>(0);
     private Set<CartItems> cartItemses = new HashSet<CartItems>(0);

    public AdType() {
    }

    public AdType(String type, Double price, Boolean status, Set<Advert> adverts, Set<CartItems> cartItemses) {
       this.type = type;
       this.price = price;
       this.status = status;
       this.adverts = adverts;
       this.cartItemses = cartItemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }
    public Set<CartItems> getCartItemses() {
        return this.cartItemses;
    }
    
    public void setCartItemses(Set<CartItems> cartItemses) {
        this.cartItemses = cartItemses;
    }




}


