package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date dateTime;
     private Double total;
     private Set<InvoiceHasAdvert> invoiceHasAdverts = new HashSet<InvoiceHasAdvert>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Date dateTime, Double total, Set<InvoiceHasAdvert> invoiceHasAdverts) {
       this.user = user;
       this.dateTime = dateTime;
       this.total = total;
       this.invoiceHasAdverts = invoiceHasAdverts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set<InvoiceHasAdvert> getInvoiceHasAdverts() {
        return this.invoiceHasAdverts;
    }
    
    public void setInvoiceHasAdverts(Set<InvoiceHasAdvert> invoiceHasAdverts) {
        this.invoiceHasAdverts = invoiceHasAdverts;
    }




}


