package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1



/**
 * InvoiceHasAdvert generated by hbm2java
 */
public class InvoiceHasAdvert  implements java.io.Serializable {


     private Integer id;
     private Advert advert;
     private Invoice invoice;
     private Double price;
     private Double qty;
     private String adtype;

    public InvoiceHasAdvert() {
    }

	
    public InvoiceHasAdvert(Advert advert, Invoice invoice) {
        this.advert = advert;
        this.invoice = invoice;
    }
    public InvoiceHasAdvert(Advert advert, Invoice invoice, Double price, Double qty, String adtype) {
       this.advert = advert;
       this.invoice = invoice;
       this.price = price;
       this.qty = qty;
       this.adtype = adtype;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Advert getAdvert() {
        return this.advert;
    }
    
    public void setAdvert(Advert advert) {
        this.advert = advert;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getAdtype() {
        return this.adtype;
    }
    
    public void setAdtype(String adtype) {
        this.adtype = adtype;
    }




}


