package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MainCatagory generated by hbm2java
 */
public class MainCatagory  implements java.io.Serializable {


     private Integer id;
     private String catagory;
     private Boolean status;
     private Set<Advert> adverts = new HashSet<Advert>(0);
     private Set<Page> pages = new HashSet<Page>(0);
     private Set<SubCatagory> subCatagories = new HashSet<SubCatagory>(0);

    public MainCatagory() {
    }

    public MainCatagory(String catagory, Boolean status, Set<Advert> adverts, Set<Page> pages, Set<SubCatagory> subCatagories) {
       this.catagory = catagory;
       this.status = status;
       this.adverts = adverts;
       this.pages = pages;
       this.subCatagories = subCatagories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }
    public Set<Page> getPages() {
        return this.pages;
    }
    
    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }
    public Set<SubCatagory> getSubCatagories() {
        return this.subCatagories;
    }
    
    public void setSubCatagories(Set<SubCatagory> subCatagories) {
        this.subCatagories = subCatagories;
    }




}


