package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCatagory generated by hbm2java
 */
public class SubCatagory  implements java.io.Serializable {


     private Integer id;
     private MainCatagory mainCatagory;
     private String catagory;
     private Boolean status;
     private Set<Advert> adverts = new HashSet<Advert>(0);

    public SubCatagory() {
    }

	
    public SubCatagory(MainCatagory mainCatagory) {
        this.mainCatagory = mainCatagory;
    }
    public SubCatagory(MainCatagory mainCatagory, String catagory, Boolean status, Set<Advert> adverts) {
       this.mainCatagory = mainCatagory;
       this.catagory = catagory;
       this.status = status;
       this.adverts = adverts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MainCatagory getMainCatagory() {
        return this.mainCatagory;
    }
    
    public void setMainCatagory(MainCatagory mainCatagory) {
        this.mainCatagory = mainCatagory;
    }
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }




}


