package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Boolean status;
     private Set<User> users = new HashSet<User>(0);
     private Set<UserTypeHasInterfaces> userTypeHasInterfaceses = new HashSet<UserTypeHasInterfaces>(0);

    public UserType() {
    }

    public UserType(String type, Boolean status, Set<User> users, Set<UserTypeHasInterfaces> userTypeHasInterfaceses) {
       this.type = type;
       this.status = status;
       this.users = users;
       this.userTypeHasInterfaceses = userTypeHasInterfaceses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<UserTypeHasInterfaces> getUserTypeHasInterfaceses() {
        return this.userTypeHasInterfaceses;
    }
    
    public void setUserTypeHasInterfaceses(Set<UserTypeHasInterfaces> userTypeHasInterfaceses) {
        this.userTypeHasInterfaceses = userTypeHasInterfaceses;
    }




}


