package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1



/**
 * UserTypeHasInterfaces generated by hbm2java
 */
public class UserTypeHasInterfaces  implements java.io.Serializable {


     private Integer id;
     private Interfaces interfaces;
     private UserType userType;

    public UserTypeHasInterfaces() {
    }

    public UserTypeHasInterfaces(Interfaces interfaces, UserType userType) {
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


