package POJOS;
// Generated Dec 22, 2016 8:20:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private UserType userType;
     private String userName;
     private String tel;
     private String password;
     private String email;
     private String securityCode;
     private Boolean actStatus;
     private String onStatus;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Page> pages = new HashSet<Page>(0);
     private Set<AdReview> adReviews = new HashSet<AdReview>(0);
     private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);
     private Set<Advert> adverts = new HashSet<Advert>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<Message> messages = new HashSet<Message>(0);

    public User() {
    }

	
    public User(UserType userType, String email) {
        this.userType = userType;
        this.email = email;
    }
    public User(UserType userType, String userName, String tel, String password, String email, String securityCode, Boolean actStatus, String onStatus, Set<Cart> carts, Set<Page> pages, Set<AdReview> adReviews, Set<LoginSession> loginSessions, Set<Advert> adverts, Set<Invoice> invoices, Set<Message> messages) {
       this.userType = userType;
       this.userName = userName;
       this.tel = tel;
       this.password = password;
       this.email = email;
       this.securityCode = securityCode;
       this.actStatus = actStatus;
       this.onStatus = onStatus;
       this.carts = carts;
       this.pages = pages;
       this.adReviews = adReviews;
       this.loginSessions = loginSessions;
       this.adverts = adverts;
       this.invoices = invoices;
       this.messages = messages;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    public Boolean getActStatus() {
        return this.actStatus;
    }
    
    public void setActStatus(Boolean actStatus) {
        this.actStatus = actStatus;
    }
    public String getOnStatus() {
        return this.onStatus;
    }
    
    public void setOnStatus(String onStatus) {
        this.onStatus = onStatus;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Page> getPages() {
        return this.pages;
    }
    
    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }
    public Set<AdReview> getAdReviews() {
        return this.adReviews;
    }
    
    public void setAdReviews(Set<AdReview> adReviews) {
        this.adReviews = adReviews;
    }
    public Set<LoginSession> getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set<LoginSession> loginSessions) {
        this.loginSessions = loginSessions;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }




}


